guild-id: 709740759552884788

commands:
  message:
    binfiles:
      enabled: true
    googleThat:
      enabled: true
  slash:
    clear:
      enabled: true
      limit: 10
    select-roles:
      enabled: false
      initial-response:
        text: Select your roles.
      updated-response:
        text: Roles updated!
      roles:
        - id: 893271631189934080
          emoji:
            name: üì°
        - id: 1072035607372644353
          emoji:
            name: ‚ùó
        - id: 1072035568663408640
          emoji:
            name: üõí
    custom:
      - name: custom-embed-command
        description: A custom embed command defined in the config
        response:
          embeds:
            - title: The best
              author:
                name: Donald Trump
                icon: https://imgur.com/wL84u1p.png
              description: |-
                I know more about programming than anybody, believe me. It's tremendous, just tremendous. The best code you've ever seen, trust me.
              color: "#0009b5"
              footer:
                text: Generated by Chat GPT and Craiyon
      - name: custom-text-command
        description: A custom message command defined in the config
        response:
          text: |-
            A multi-line message
            sent a plain text.
      - name: disabled-command
        description: A command that's disabled
        enabled: false
        response:
          text: You shouldn't see this!

auto-actions:
  - media:
      - TEXT
      - FILE
      - BIN
      - IMAGE
    bots: false
    actions:
      - pattern: "Hello there!"
        responses:
          - embeds:
              - title: Hi!
                description: How are you?
        reactions:
          - name: üöÇ

statistic-channels: [ ]
#  - channel-id: 1070824774009368636
#    format: "Train People: %s"
#    statistic: YOUTUBE_SUBS
#    data: UCHUb_Wty4v2ddZqbxdqOmxA

codebin:
  upload: LUCKO_PASTE
  services:
    HASTEBIN_LEGACY:
      - paste.md-5.net
      - paste.helpch.at
    SOURCE_BIN:
      - sourceb.in
    LUCKO_PASTE:
      - paste.insprill.net
      - paste.mufin.live
    PASTEBIN:
      - pastebin.com

audit:
  audit-channel: 793644931943497809
  ignore-channels: [ ]
  log-bots: false
  events:
    members:
      banned: true
      unbanned: true
      joined: true
      left: true
      voice: true
      updated:
        enabled: true
        nickname: true
        username: true
        avatar: true
        memberAvatar: true
        banner: true
        discriminator: true
    messages:
      deleted: true
      edited: true
      invite-posted: true
    server:
      role:
        created: true
        deleted: true
      channel:
        created: true
        deleted: true

restricted-channels: [ ]
#  - channel-id: 1075925445440180265
#    message:
#      text: |-
#        This channel is restricted to members with the role `@Train People`.
#    types:
#      - TEXT
#      - IMAGE
